### ISSUE TITLE
Installation with AssetMapper

### ISSUE THREAD

**Issue by klkvsk** [Ehyiah/ux-quill#12]
It's unclear how to get started with ux-quill when using Symfony's AssetMapper component.
There's no package.json in project root, so `npm/yarn install` is not appliable.
Instead what I tried to do was:
- `symfony console importmap:require quill/dist/quill.snow.css` to fetch required dependency file from [ux-quill/assets/package.json](https://github.com/Ehyiah/ux-quill/blob/12d23b645e90614616c37871b13afed37a91ad86/assets/package.json#L15)
- `symfony console importmap:install` (not sure if this was required, but ran anyway)
- ensure `{{ importmap("app") }}` exists in template

./assets/app.js and ./assets/bootstrap.js is generated by symfony/stimulus-bundle's install recipe:
```
// app.js
import './bootstrap.js';

// bootstrap.js
import { startStimulusApp } from '@symfony/stimulus-bundle';
const app = startStimulusApp();
```

importmap.php is generated after `importmap:` commands:
```
return [
    'app' => [
        'path' => './assets/app.js',
        'entrypoint' => true,
    ],
    '@hotwired/stimulus' => [
        'version' => '3.2.2',
    ],
    '@symfony/stimulus-bundle' => [
        'path' => './vendor/symfony/stimulus-bundle/assets/dist/loader.js',
    ],
    'quill/dist/quill.snow.css' => [
        'version' => '1.3.7',
        'type' => 'css',
    ],
];
````

WIth this it should have been enough for ux-quill to be automatically loaded.
However, there's this error at run time:
```
Uncaught SyntaxError: The requested module '../../@ehyiah/ux-quill/controller.js' does not provide an export named 'default' 
```

I've checked the controller does provide default export, so not sure if it's a problem in js code, or in importmap config.

**Comment by Ehyiah** [comment]
I'm working on it,
I didn't really have time up to now to test it with the new AssetMapper, as I was using it only with webpack encore on my projects.

There seems to have some missing required for importmaps for an auto-install out of the box. I'll fix them.

But I think the major problem is how the typescript is compiled for the last error you mentionned.
I'll try to fix this as soon as possible.

**Comment by klkvsk** [comment]
Works out of box now, thank you!
