### ISSUE TITLE
Quill showing colon(:) instead of periode(.), only on the fisrt one.

### ISSUE THREAD

**Issue by Pimous972** [Ehyiah/ux-quill#23]
When writing text in the editor, the first period is replaced by a colon. The following ones are okay.

Do you have a solution ?

**Comment by Ehyiah** [comment]
Can one of you provide maybe a short video or a simple project with this problem ? 
or maybe copy paste me a sentence that cause a problem that i will try to retype. I re-tried to reproduce this problem but without success.

Did you provide any custom options maybe when initializing quill ?

Or can you reproduce the problem on quill playground ? https://v1.quilljs.com/playground/

I'm working on a version compatible with the upcoming v2 of quill, maybe you can try this branch https://github.com/Ehyiah/ux-quill/tree/dev/quill-v2-beta and see if the problem persist ?

**Comment by axelr7x** [comment]
The new version (v2) of QuillJs resolved everything ;)

**Comment by Ehyiah** [comment]
Wonderful, thanks for the feedback

**Comment by Pimous972** [comment]
Hello i also update to QuillJS v2 and it's OK, thanks for the job !
