### ISSUE TITLE
B and I button but not anything else

### ISSUE THREAD

**Issue by keoozDan** [Ehyiah/ux-quill#24]
Hi,
is it normal that i just have the Bold and Italic button but not all other ?
Best regards

![image](https://github.com/Ehyiah/ux-quill/assets/43570407/4c54db1e-9609-4200-ab12-f182eedcfab8)

**Comment by keoozDan** [comment]
I see that i can add other type of field but could we have standard full option without add on each Form ?

I can't add the ListFIeld

**Comment by Ehyiah** [comment]
> I see that i can add other type of field but could we have standard full option without add on each Form ?
> 
> I can't add the ListFIeld

A all-in field will be present in the coming v2 release with all the fields enabled.

**Comment by Ehyiah** [comment]
> I see that i can add other type of field but could we have standard full option without add on each Form ?
> 
> I can't add the ListFIeld

I just publish a new tag with the fix for the ListField.
As the v2 may take some days/weeks to come out.

**Comment by Ehyiah** [comment]
V2 is out
ListField is fixed on v1 and v2 version.
The buildWithAllFields is also available in the v2 version. 
thanks
