### ISSUE TITLE
AssetMapper - require quill2-emoji

### ISSUE THREAD

**Issue by robiinho** [Ehyiah/ux-quill#29]
Hi,

i had an error in the console output, the following was required :  quill2-emoji

php bin/console importmap:require quill2-emoji

Now there is no more error,

Robin.

**Comment by robiinho** [comment]
Hello,
i did an update trough assetmapper (outdates + update) and it wasn't enough.

**Comment by Ehyiah** [comment]
Hi,
I can't reproduce the problem.
Can you tell me what version of the bundle did you install ?

Maybe you have a repo for your project i can try to install and see if I can reproduce the same problem ?
