### ISSUE TITLE
modules.js

### ISSUE THREAD

**Issue by GuillaumeDelahaye** [Ehyiah/ux-quill#33]
Hey,

Thanks for ux-quill !

I'm starting to experiment with your bundle, but after reading the doc a few more times, it seems i hit a wall.

The only way i found to make it work i to edit your controller.js file to comment everything related to a file named modules.js.
From what i can tell, file seem to be missing.

Did i miss anything ?

**Comment by Ehyiah** [comment]
Hi, no there seem to be a problem with the latest release.
Could you try the previous released version ? The 2.0.3 and see if you got the same problem ? 
I'll try to fix the 2.0.4 ASAP.

**Comment by Ehyiah** [comment]
forgot to ask, but what are you using ? webpack or assetMapper to install the bundle?

**Comment by Ehyiah** [comment]
You can download the new 2.0.5 release, the missing file is well added :-)
Please tell me if this fixed your problem.

**Comment by GuillaumeDelahaye** [comment]
> Hi, no there seem to be a problem with the latest release. Could you try the previous released version ? The 2.0.3 and see if you got the same problem ? I'll try to fix the 2.0.4 ASAP.
> 
> edit: there is indeed missing build files, didn't add these to vcs ... really sorry for this.

No worries !

> forgot to ask, but what are you using ? webpack or assetMapper to install the bundle?

assetMapper

>You can download the new 2.0.5 release, the missing file is well added :-)
>Please tell me if this fixed your problem.

I'm going to check the new release asap and i will get back to you :)

**Comment by GuillaumeDelahaye** [comment]
Hi, sorry for the delay, everything works out of the box now, no more modules.js problem.
Thanks for the fix !
