### ISSUE TITLE
Configuration of the toolbar(s)

### ISSUE THREAD

**Issue by Joonioh** [Ehyiah/ux-quill#35]
Hi,

Thank you for your work.

I just tried to run it on our symfony project and it seems to work fine, but I was trying to find a way to configure it like CKEditor (trying to find an alternative to it), where there's a yaml file containing an array of the buttons you want to have in your toolbars, and you can have as many different toolbars as you want, like this : 

```
my_toolbar_advanced: [["Bold", "Italic", "Underline", "TextColor", "BGColor", "RemoveFormat", "-", "Undo", "Redo", "-", "Table", "NumberedList", "BulletedList", "-", "Outdent", "Indent", "-", "Maximize"]]
my_toolbar_basic: [ [ "Bold", "Italic", "RemoveFormat", "-", "Maximize" ]]
my_toolbar_empty: [["Maximize"]]
```

I tried to look in the readme and the quill doc but I don't think I found the file in question (or I missed it).

In the meantime I created my own type that implements your QuillGroupInterface and have a method for each toolbar I want to implement, seems to be the closest to what I'm talking about, but if there's a simpler way, I'm open to it.

Have a good day.

**Comment by Ehyiah** [comment]
Hello, thanks for using this bundle !

Sorry, but there is indeed no way at the moment (maybe a future feature if the community find it useful and necessary) to preconfigure a toolbar in a yaml format.
The best way to do this is indeed to create a FormType (or multiple FormTypes) and preconfigure it.

I didn't find it necessary to have an external file (like a yaml) to configure toolbars as I think it is very easy to create a formType that can be reused and configured to have multiple toolbars.

**Comment by Joonioh** [comment]
Alright, thanks for the answer. I'll close the issue then.
