### ISSUE TITLE
ClipboardModule not found

### ISSUE THREAD

**Issue by davidromani** [Ehyiah/ux-quill#37]
As described [here](https://github.com/Ehyiah/ux-quill?tab=readme-ov-file#extend-quill-stimulus-controller) it seems that there is a missing `ClipboardModule` module in `Ehyiah\QuillJsBundle\DTO\Options\Modules` namespace.

**Comment by Ehyiah** [comment]
Hello,
That's right, It's an error of the documentation, the clipboard module does not need to be configured in the PHP form.
See instead the Extend Quill stimulus controller doc chapter if you need to customize its behaviour.

I will update the doc asap.

Thanks for the report.
